### ISSUE TITLE
Feature: User can scroll through and select from a list of activities to do #1

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ajax-project#1]
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/122063836/221995663-c6e9244e-69d5-4f5c-a612-4f58af609351.png)
![image](https://user-images.githubusercontent.com/122063836/221995755-f82b0f43-0546-4347-97f8-c40da3558e01.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a new index.html file with a skeleton and a title of "Yellowstone Activities"
  - [x] Create script tags at the bottom of the body for two .js files: a main.js and a data.js.  In the head connect your styles.css file.
- [x] Create a main.js file and a data.js file 
  - [x] In the data.js file, create an object assigned to a variable "data".  Create these properties in the object to start with: savedActivities, editing
- [x] Create a styles.css file and connect it to index.html
- [x] Open the index.html file in the broswer, and the console, and make sure all the files are functioning correctly
- [x] In index.html, create a div element with the class "container"
- [x] Inside the container, create a nav element with an h2 element and an "a" element inside 
- [x] Write CSS code so that it matches the figma example (less the dropdown menu), and set a background image based on the figma
- [x] In the HTML file, create a dropdown menu using the "select" element, with with a couple "option" elements inside.  Once it is functioning correctly, proceed to the next step to create entries from API data
- [x] The following step requires an event listener for when the DOM finishes loading, so in the main.js file, set up an event handler with a callback function which does the following: 
  - [x] Accesses the DOM and replicate the above-created drop-down menu entry, so that it can access the API and populate the menu items with the "title" property of each object on on the API.  Test it to ensure it is properly functioning.
- [x] Finish issue by doing the following:
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
