### ISSUE TITLE
Feature: User can view information on their selected activity #2

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ajax-project#2]
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/122063836/222251571-f2799e35-4242-45ca-a36a-146ec060dc3e.png)
![image](https://user-images.githubusercontent.com/122063836/222251778-55f9130e-f78a-4d7d-b1a3-89f56b4bfac5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] In index.html, add a "hide" class to the home screen content, and create the corresponding css to hide the content.  For now, manually hide the content. 
- [x] Create html which models the figma for this feature: 
  - [x] In the nav section, create an `<a>` element named "Home" (Later, code will be added to hide this element will hide the current page and take you back to the home page where activities can be selected.)
  - [x] Create the "selected activity" header 
  - [x] Create a card displaying a selected item as in the figma.  Later, the info categories (Location, Duration, Accessibility, Fees) will populate with info from the API.  The card should have:
    - [x] An image element, an h2 for the title with activity name, and remaining information in p elements
    - [x] Inside the card create an `<a>` element for "Add to My Activities" 
- [x] Write CSS code as necessary to match the figma
- [x] Put the dropdown into a form, and add a button
- [x] Once the entry matches the figma on both desktop and mobile, delete the text in each info category from the HTML (i.e. location info, duration info etc.)
- [x] When an activity is selected from the home screen, the "selected activity" screen needs to appear, with the home screen disappearing.  Create an event handler for when an item is selected from the home screen.  It should: 
  - [x] Grab the object information from the selected item and put that information into data.viewing (create this property in the data object in data.js)
  - [x] Switch from the home screen to the "Selected Activity" screen by changing data.view to "selected-activities-view"
    - [x] For this to work, a viewswap function needs to be created.  Create a viewswap function which changes: 
      - [x] to "home-view" when the "home" button is clicked
      - [x] to "selected-activity-view" when an activity is selected
      - [x] to "my-activities-view" when "my activities" is clicked  
  - [x] Create an "activity" card using the information in data.viewing and render it on the "selected activity" screen upon pressing the "go" button on the home view screen
- [x] Now we need to make sure that when the page is reloaded, the same screen & info appears (i.e. you stay right where you are).  For this, everything in the data object must be stored in local storage upon page unload, and upon reloading that data in local storage must be accessed, parsed, and put back into the data object.  Do the following: 
  - [x] Use as a model the code at "https://github.com/colin-macrae/code-journal/blob/main/js/data.js" for the next two steps below
  - [x] Add another property, "savedActivities", to the data object 
  - [x] Add a "beforeunload" event listener whose callback does a JSON.strigify(data) and sends the strigified object to local storage: 
  - [x] Get the stringed data in local storage (for when page loads), parse it, and set it to the data object

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
