### ISSUE TITLE
Feature: User can save selected activities to a likes list #3

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ajax-project#3]
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/122063836/222600711-af17a3dc-181b-4a7b-93c2-c7fa8a059ee1.png)
![image](https://user-images.githubusercontent.com/122063836/222601424-5a2af2a6-9a0a-4917-900a-65724628eefd.png)
![image](https://user-images.githubusercontent.com/122063836/222251778-55f9130e-f78a-4d7d-b1a3-89f56b4bfac5.png)
![image](https://user-images.githubusercontent.com/122063836/222602064-e06685bd-f04d-49d1-b77c-1ba895ea0be2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create functionality on the "home" button so that it takes you to the home view when clicked.  Do the following:
  - [x] Query select the home button.
  - [x] Create an addEventListener whose callback function: 
    - [x] Viewswaps to home screen and 
    - [x] reset data.viewing to { }
- [x] Create a "No Saved Activities" function with a toggle function for it, which toggles off whenever data.savedActivities is not empty
- [x] In HTML and CSS, create a "My Activities" screen according to the figma, with dummy data filling out the card, by doing the following:  
  - [x] Start by copying almost all the code from the "selected activity" screen
  - [x] Change the title to "My Activities"
  - [x] Change the "Add to My Activities" button to "Remove from My Activities" and use a "#" placeholder for the link
- [x] Once the above step is finished , create a duplicate on the DOM and test it.  When it's functioning properly, delete the dummy entry. 
- [x] Create an event handler with a callback function on the "Add to My Activities" button so that when clicked, it A) adds the activity to data.savedActivities and B) (using viewswap) takes you to the populated "My Activities" screen.  (you need to add a couple lines of code to the viewswap function to finish that).  Here are the steps:   
  - [x] manually add a "nextSavedActivityId" whose value is the number 1 to the data object 
  - [x] Create a listener and in the callback function: 
    - [x] Remove the "my activities" button from the navbar by hiding it when the screen viewswaps  
    - [x] add a "savedActivityId" property to the object in data.viewing, and set its value to the value of data.nextSavedActifityId     
    - [x] Get that viewed/added object from data.viewing     
    - [x] unshift the viewed/added activity object into data.savedActivities (unshift it so that it goes to the beginning (if that is not allowed for the first object, push it and later unshift objects when data.savedActivities is NOT empty)).
    - [x] hide the 'selected activity' screen 
  - [x] Create a loop which renders all objects in data.savedActivities using $renderSavedActivities function and renders the DOM tree for all saved cards
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
