### ISSUE TITLE
Feature: User can write and save notes for an activity on their lists #4

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ajax-project#4]
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![4546354354](https://user-images.githubusercontent.com/122063836/222923168-0e8db463-eefe-41d6-8c5d-a97cddb4fe7e.PNG)
![465654634354](https://user-images.githubusercontent.com/122063836/222923187-3585bce8-9944-4ec4-82c2-2352b936f3f0.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] create in index.html a "writing/editing" screen.  this does not need to be on the dom. 
- [x] change the button text to "Write/Edit"
  - [ ] Add a "data-saved-activity-id" attribute to each entry (on the button is fine), and set its value when the entry is created (add this functionality to the "add to my activities" button/function
- [x] write a 'notes section' on the dom for all saved entries (empty but to be filled if notes written)
  - [x] for this you can manipulate the code already written, change it to a div/p instaed of a form 
 - [x] when the button is clicked, it gets that entry by doing the following: 
     - [x] use bubbling to find the the text content of the nearest h2 element (which is the activity's title) 
     - [x] use that text content to search through all data.savedActivities.title
     - [x] when that is found, get the whole object and assign it to data.editing  
     - [x] check if previous notes have been written, and if so, populate the form
     - [x] render it in order to fill out the entry for editing/note writing (you need to create a function for rendering it)
     - [x] swap to the editing screen
- [x] create functionality on the save button to do the following
  - [x] create a data.editing.notes property 
  - [x] set the value in the form, notes to data.editing.notes
  - [x] use the title in data.editing.notes to compare to (by looping through all data.savedActivities) and find the entry in data.savedActivities.  
  - [x] when it is found, set the object in data.editing as the value of the matching object in data.savedActivities
  - [x] add functionality to the dom or wherever needed so that the entry renders, with the notes there, in the 'my activities' section/screen
  - [x] viewswaps to the 'my activities' screen
- [x] add functionality/a conditional statement which prevents users from saving the same activity (title) twice: 
  - [x] in the add activity button function, have it loop through the current activities in savedActivities, and if it finds a match, prevent the save using "return" in the function
  - [x] set an alert telling the user duplicates aren't allowed 

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
