### ISSUE TITLE
Feature: User can Remove items from their lists #6

### ISSUE THREAD

**Issue by colin-macrae** [colin-macrae/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![4546354354](https://user-images.githubusercontent.com/122063836/224456955-f44df6ff-c2d8-424f-86ef-4f0ff999772a.PNG)
![465654634354](https://user-images.githubusercontent.com/122063836/224456964-d46ec894-6900-4433-9274-8ba0465add45.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add an event listener for the 'click' event on the "remove" buttons.  add it to the nearest shared container for the title (h2) and the button, and in the listener's callback function: 
  - [x] get the text content of the closest h2 element.  if you have problems as you did in the previous issue, see Shawn's code for a solution on accessing that text content 
  - [x] loop through all the the data.savedActivities objects, searching the "title" property for each, until a matching value is found 
  - [x] delete the matching entry with the splice method, like so: data.savedActivities.splice(i, 1);  
  - [x] add an alert confirming the entry has been deleted 
  - [x] swap back to the "my activities" view  

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
